### ISSUE TITLE
大佬可以留个联系方式吗，有个问题请教

### ISSUE THREAD

**Issue by Dyrookie** [1150037361/SpringScan#4]

**Comment by 1150037361** [comment]
啥问题直接问就行

**Comment by n1i1e1** [comment]
java.lang.RuntimeException: java.lang.StackOverflowError
	at burp.Zbq1.ZD(Unknown Source)
	at burp.Z_e.Zs(Unknown Source)
	at burp.Zttx.Zh(Unknown Source)
	at burp.Zpob.addSuiteTab(Unknown Source)
	at burp.Zfsw.addSuiteTab(Unknown Source)
	at burp.Zohj.addSuiteTab(Unknown Source)
	at burp.Ze8b.addSuiteTab(Unknown Source)
	at burp.BurpExtender$3.run(BurpExtender.java:142)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:318)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:771)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:722)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:716)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:741)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
为什么报错阿，不是中文路径

**Comment by 1150037361** [comment]
@n1i1e1 你这个可能是burp的版本不对

**Comment by admin1test** [comment]
我也这样报错，能否支持下新版的burp

**Comment by admin1test** [comment]
@1150037361

**Comment by admin1test** [comment]
java.lang.RuntimeException: java.lang.StackOverflowError
	at burp.Zdy0.Zp(Unknown Source)
	at burp.Zdww.ZZ(Unknown Source)
	at burp.Zcax.ZX(Unknown Source)
	at burp.Zd6o.addSuiteTab(Unknown Source)
	at burp.Zii9.addSuiteTab(Unknown Source)
	at burp.Zmb.addSuiteTab(Unknown Source)
	at burp.Ztd2.addSuiteTab(Unknown Source)
	at burp.BurpExtender$3.run(BurpExtender.java:142)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:318)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:771)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:722)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:716)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:741)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)

**Comment by 1150037361** [comment]
@admin1test 哥们我试了试最新版本的都没问题，你不会拿源码编译的吧

**Comment by 1150037361** [comment]
实在不行可以加我qq：1150037361
